sudo: false
language: python
os:
  - linux

matrix:
  fast_finish: true

  include:
    - python: 2.7
      env: TOX_ENV=py27

    - python: 3.6
      env: TOX_ENV=py36

install:
  - pip install tox

script:
  - tox -e $TOX_ENV